[build]
base = "website/"
command = "npm run build"
functions = ".netlify/functions"
publish = "dist"

[[plugins]]
package = "netlify-plugin-gridsome-cache"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[dev]
autoLaunch = true
command = "gridsome develop"
framework = "gridsome"
port = 3850
publish = "dist"

[[redirects]]
force = true
from = "/training/*"
status = 200
to = "/index.html"
