[build]
base = "website/"
command = "npm run build"
functions = ".netlify/functions"
publish = "dist"

[[plugins]]
package = "netlify-plugin-gridsome-cache"

[[plugins]]
package = "@netlify/plugin-lighthouse"
