name: Release
on:
  release:
    types: [published]
jobs:
  test:
    runs-on: ubuntu-20.04
    name: Python ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ['3.7.x', '3.8.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: sdk
        run: make install-deps
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Test
        working-directory: sdk
        run: make test
  release:
    runs-on: ubuntu-20.04
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: x64
    - run: pip3 install poetry
      working-directory: sdk
    - run: poetry build
      working-directory: sdk
    - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
      working-directory: sdk
